#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs
#
[uefi_fd]
base = 0x8F000000
size = 0x200000

#
# Android Boot Image Kernel Configs
#
[boot_image_kernel]
kernel_compression = "none"
append_dtb         = false

#
# Android Boot Image Configs
#
[boot_image]
header_version = 1
