#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs
#
[uefi_fd]
base = 0xBAB00000
size = 0x300000

#
# Android Boot Image Kernel Configs
#
[boot_image_kernel]
kernel_compression = "gzip"
append_dtb         = false

#
# Android Boot Image Configs
#
[boot_image]
dtb            = "Resources/DTBs/dm2q.dtb"
header_version = 2
