#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs
#
[uefi_fd]
fd_base = 0x5FC00000
fd_size = 0x300000

#
# Android Boot Image Configs
#
[boot_image]
kernel_compression = "gzip"
dtb_location       = "kernel"
header_version     = 1
