#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs
#
[uefi_fd]
base = 0xE8000000
size = 0x200000

#
# Android Boot Image Kernel Configs
#
[boot_image_kernel]
kernel_compression = "none"
append_dtb         = false

#
# Android Boot Image Configs
#
[boot_image]
dtb            = "Resources/DTBs/x1s.dtb"
header_version = 2
